### ISSUE TITLE
There is no help for owltools --gaf-term-counts and --merge-support-ontologies

### ISSUE THREAD

**Issue by koefoed** [owlcollab/owltools#125]
The owltools help (```owltools -h```) states

> Commands/Options
>  (type 'owltools COMMAND -h' for more info)

but ```owltools --gaf-term-counts -h``` results in
```sh
$ owltools --gaf-term-counts -h 
Exception in thread "main" java.lang.NullPointerException
	at owltools.cli.GafCommandRunner.gafTermCounts(GafCommandRunner.java:690)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at owltools.cli.CommandRunner.runSingleIteration(CommandRunner.java:3891)
	at owltools.cli.CommandRunnerBase.run(CommandRunnerBase.java:76)
	at owltools.cli.CommandRunner.run(CommandRunner.java:237)
	at owltools.cli.CommandRunnerBase.run(CommandRunnerBase.java:68)
	at owltools.cli.CommandRunner.run(CommandRunner.java:237)
	at owltools.cli.CommandLineInterface.main(CommandLineInterface.java:12)
```

I think this is an error?

Also the same thing happens for ```--merge-support-ontologies```
```
$ owltools --merge-support-ontologies -h 
Exception in thread "main" java.lang.NullPointerException
	at owltools.cli.CommandRunner.runSingleIteration(CommandRunner.java:531)
	at owltools.cli.CommandRunnerBase.run(CommandRunnerBase.java:76)
	at owltools.cli.CommandRunner.run(CommandRunner.java:237)
	at owltools.cli.CommandRunnerBase.run(CommandRunnerBase.java:68)
	at owltools.cli.CommandRunner.run(CommandRunner.java:237)
	at owltools.cli.CommandLineInterface.main(CommandLineInterface.java:12)
```

**Comment by hdietze** [comment]
Yes, as already stated documentation is limited. We will fix the exceptions and add a help message for the given commands.
