### ISSUE TITLE
NullPointerException in OboBasicDagCheck

### ISSUE THREAD

**Issue by cmungall** [owlcollab/owltools#137]
```
2015-09-24 08:28:53,033 INFO  (OboOntologyReleaseRunner:21) Start - Verifying DAG requirement for OBO Basic.
cannot handle:ObjectHasSelf(<http://purl.obolibrary.org/obo/RO_0002465>)
cannot handle:ObjectHasSelf(<http://purl.obolibrary.org/obo/RO_0002465>)
cannot handle:ObjectHasSelf(<http://purl.obolibrary.org/obo/RO_0002465>)
cannot handle:ObjectHasSelf(<http://purl.obolibrary.org/obo/RO_0002465>)
cannot handle:ObjectHasSelf(<http://purl.obolibrary.org/obo/RO_0002465>)
cannot handle:ObjectHasSelf(<http://purl.obolibrary.org/obo/RO_0002465>)
cannot handle:ObjectHasSelf(<http://purl.obolibrary.org/obo/RO_0002465>)
cannot handle:ObjectHasSelf(<http://purl.obolibrary.org/obo/RO_0002465>)
cannot handle:ObjectHasSelf(<http://purl.obolibrary.org/obo/RO_0002465>)
cannot handle:ObjectHasSelf(<http://purl.obolibrary.org/obo/RO_0002465>)
cannot handle:ObjectHasSelf(<http://purl.obolibrary.org/obo/RO_0002465>)
cannot handle:ObjectHasSelf(<http://purl.obolibrary.org/obo/RO_0002465>)
cannot handle:ObjectHasSelf(<http://purl.obolibrary.org/obo/RO_0002465>)
cannot handle:ObjectHasSelf(<http://purl.obolibrary.org/obo/RO_0002465>)
cannot handle:ObjectHasSelf(<http://purl.obolibrary.org/obo/RO_0002465>)
cannot handle:ObjectHasSelf(<http://purl.obolibrary.org/obo/RO_0002465>)
cannot handle:ObjectHasSelf(<http://purl.obolibrary.org/obo/RO_0002465>)
cannot handle:ObjectHasSelf(<http://purl.obolibrary.org/obo/RO_0002465>)
2015-09-24 08:28:53,475 ERROR (OboOntologyReleaseRunner:37) Stopped Release process. Reason: null
java.lang.NullPointerException
        at owltools.util.MappingTarjan.notEquals(MappingTarjan.java:55)
        at owltools.util.AbstractTarjan.tarjan(AbstractTarjan.java:89)
        at owltools.util.AbstractTarjan.tarjan(AbstractTarjan.java:77)
        at owltools.util.AbstractTarjan.executeTarjan(AbstractTarjan.java:38)
        at owltools.ontologyrelease.OboBasicDagCheck.findCycles(OboBasicDagCheck.java:43)
        at owltools.ontologyrelease.OboOntologyReleaseRunner.handleSimpleOntology(OboOntologyReleaseRunner.java:1280)
        at owltools.ontologyrelease.OboOntologyReleaseRunner.createRelease(OboOntologyReleaseRunner.java:1058)
        at owltools.ontologyrelease.OboOntologyReleaseRunner.createRelease(OboOntologyReleaseRunner.java:494)
        at owltools.ontologyrelease.OboOntologyReleaseRunner.main(OboOntologyReleaseRunner.java:193)
2015-09-24 08:28:53,478 INFO  (OboOntologyReleaseRunner:21) deleting lock file
```

To recreate:
```
ontology-release-runner --catalog-xml catalog-v001.xml  --skip-format owx --run-obo-basic-dag-check --error-report envo-errors.txt $< --allow-overwrite --asserted --simple
```

on envo-edit.owl in https://github.com/EnvironmentOntology/envo/tree/master/src/envo

**Comment by hdietze** [comment]
Pushed a fix. The check runs now with ENVO as input.
It detected now three cycles, not sure if these are actually valid, or if we need to restrict the axiom types included in the check.
