### ISSUE TITLE
Error when saving as functional syntax

### ISSUE THREAD

**Issue by dosumis** [owlcollab/owltools#148]
Trying to convert this file to functional syntax works with Protege but not with with OWLtools CLI 

https://github.com/VirtualFlyBrain/VFB_owl/blob/master/src/owl/fbbt_vfb_ind_prc_nr.owl

owltools fbbt_vfb_ind_prc_nr.owl -o -f ofn vfb.ofn
=>
Feb 11, 2016 4:11:23 PM org.semanticweb.owlapi.util.CollectionFactory sortOptionally
WARNING: Misbehaving triple comparator, leaving triples unsorted: [ ... < long list of triples> ]
java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.util.ComparableTimSort.mergeLo(ComparableTimSort.java:740)
	at java.util.ComparableTimSort.mergeAt(ComparableTimSort.java:477)
	at java.util.ComparableTimSort.mergeCollapse(ComparableTimSort.java:402)
	at java.util.ComparableTimSort.sort(ComparableTimSort.java:209)
	at java.util.Arrays.sort(Arrays.java:1312)
	at java.util.Arrays.sort(Arrays.java:1506)
	at java.util.ArrayList.sort(ArrayList.java:1454)
	at java.util.Collections.sort(Collections.java:141)
	at org.semanticweb.owlapi.util.CollectionFactory.sortOptionally(CollectionFactory.java:111)
	at org.coode.owlapi.functionalrenderer.OWLObjectRenderer.writeAxioms(OWLObjectRenderer.java:342)
	at org.coode.owlapi.functionalrenderer.OWLObjectRenderer.visit(OWLObjectRenderer.java:265)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyImpl.accept(OWLOntologyImpl.java:1516)
	at org.coode.owlapi.functionalrenderer.OWLFunctionalSyntaxOntologyStorer.storeOntology(OWLFunctionalSyntaxOntologyStorer.java:90)
	at org.semanticweb.owlapi.util.AbstractOWLOntologyStorer.store(AbstractOWLOntologyStorer.java:182)
	at org.semanticweb.owlapi.util.AbstractOWLOntologyStorer.storeOntology(AbstractOWLOntologyStorer.java:126)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.saveOntology(OWLOntologyManagerImpl.java:1001)
	at owltools.io.ParserWrapper.saveOWL(ParserWrapper.java:226)
	at owltools.cli.CommandRunner.runSingleIteration(CommandRunner.java:3062)
	at owltools.cli.CommandRunnerBase.run(CommandRunnerBase.java:76)
	at owltools.cli.CommandRunnerBase.run(CommandRunnerBase.java:68)
	at owltools.cli.CommandLineInterface.main(CommandLineInterface.java:12)

**Comment by dosumis** [comment]
Sorry.  Need to dig out rdf xml version for you to test.  Will post a compressed one as this is large.
