### ISSUE TITLE
Failed test while building from source

### ISSUE THREAD

**Issue by rctauber** [owlcollab/owltools#168]
After getting the source and running ```mvn clean install``` in OWLTools-Parent, I ran into a failure...

```
Tests run: 2, Failures: 1, Errors: 0, Skipped: 1, Time elapsed: 0.059 sec <<< FAILURE! - in owltools.gaf.io.PseudoRdfXmlWriterTest
testRelationWriter(owltools.gaf.io.PseudoRdfXmlWriterTest)  Time elapsed: 0.008 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<...eontology.org/go#GO:[0065007"/>
    <go:is_a rdf:resource="http://www.geneontology.org/go#GO:]2000112"/>
    <go:r...> but was:<...eontology.org/go#GO:[]2000112"/>
    <go:r...>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at owltools.gaf.io.PseudoRdfXmlWriterTest.testRelationWriter(PseudoRdfXmlWriterTest.java:61)
```

It hit this failure then continued to run and sat on ```Running owltools.gaf.owl.MgiGAFOWLBridgeTest``` for about 5-6 minutes before totally failing.

Here's the final info:
```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] OWLTools-Parent .................................... SUCCESS [  0.676 s]
[INFO] OWLTools-Core ...................................... SUCCESS [01:26 min]
[INFO] OWLTools-Annotation ................................ FAILURE [09:31 min]
[INFO] OWLTools-Oort ...................................... SKIPPED
[INFO] OWLTools-Sim ....................................... SKIPPED
[INFO] OWLTools-Web ....................................... SKIPPED
[INFO] Lego ............................................... SKIPPED
[INFO] OWLTools-Solr ...................................... SKIPPED
[INFO] OWLTools-Runner .................................... SKIPPED
[INFO] OWLTools-NCBI ...................................... SKIPPED
[INFO] Golr-Client ........................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 11:22 min
[INFO] Finished at: 2016-11-04T07:44:58-04:00
[INFO] Final Memory: 40M/508M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test (default-test) on project OWLTools-Annotation: There are test failures.
```

I need OORT which it looks like doesn't come with the downloadable jars (the easy way). I also looked at #163 which had a similar error, but I am using Java 8. Here's mvn --version:
```
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T11:41:47-05:00)
Maven home: /Users/Tauber/lib/apache-maven-3.3.9
Java version: 1.8.0_71, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_71.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.11.6", arch: "x86_64", family: "mac"
```

**Comment by dosumis** [comment]
Blocker for me too.

**Comment by cmungall** [comment]
Will try and look into this today

for now you can get the jar from
https://build.berkeleybop.org/job/owltools/lastSuccessfulBuild/

@kltm - do you know why this is a yellow rather than red on jenkins?

**Comment by rctauber** [comment]
Thanks! @cmungall
