### ISSUE TITLE
Upgrade OWLTools-Solr to Solr6

### ISSUE THREAD

**Issue by cmungall** [owlcollab/owltools#194]
NOTE: this should be on a branch that is NOT merged until synchronized with GO pipeline

**Comment by kltm** [comment]
> 
> option for verbose output for owl tools? 
> 

You might want to ping @cmungall or @dougli1sqrd

**Comment by cmungall** [comment]
```
    --log-info
    --log-warning
    --log-debug
    --log-error
    --no-logging
```

**Comment by nathandunn** [comment]
Yeah, it died for me here: 

```
18-02-13 11:26:59,317 INFO  (AbstractSolrLoader:61) Server at: http://localhost:8983/solr/
2018-02-13 11:26:59,372 INFO  (SolrCommandRunner:324) Trying ontology flex load.
Exception in thread "main" java.lang.NullPointerException
	at owltools.flex.FlexCollection.wring(FlexCollection.java:196)
	at owltools.flex.FlexCollection$1.next(FlexCollection.java:248)
	at owltools.flex.FlexCollection$1.next(FlexCollection.java:236)
	at owltools.solrj.FlexSolrDocumentLoader.load(FlexSolrDocumentLoader.java:41)
	at owltools.cli.SolrCommandRunner.flexLoadOntologySolr(SolrCommandRunner.java:325)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at owltools.cli.CommandRunner.runSingleIteration(CommandRunner.java:4775)
	at owltools.cli.CommandRunnerBase.run(CommandRunnerBase.java:76)
	at owltools.cli.CommandRunnerBase.run(CommandRunnerBase.java:68)
	at owltools.cli.CommandLineInterface.main(CommandLineInterface.java:12)
```

I think I dropped a config I shouldn't have.  I'll go back through with the proper configurations.

**Comment by kltm** [comment]
This tool requires an amigo checkout and amigo config yaml files to run. Check the job configuration.
