### ISSUE TITLE
Error: "... OWLLiteralImplString cannot be cast to org.semanticweb.owlapi.model.IRI"

### ISSUE THREAD

**Issue by kimrutherford** [owlcollab/owltools#200]
Hi.  We're using owltools v0.3.0 to extract a pombe-only subset of GO.

We're using this command line:

    owltools --use-catalog go-plus.owl --reasoner elk --make-species-subset \
         -t NCBITaxon:4896 -o -f obo go-plus-pombe-only.obo

in go-svn/ontology/extensions/

We get this error:

    Exception in thread "main" java.lang.ClassCastException: uk.ac.manchester.cs.owl.owlapi.OWLLiteralImplString cannot be cast to org.semanticweb.owlapi.model.IRI
        at org.obolibrary.macro.MacroExpansionVisitor$MacroExpansions.expand(MacroExpansionVisitor.java:162)
        at org.obolibrary.macro.MacroExpansionVisitor$MacroExpansions.<init>(MacroExpansionVisitor.java:122)
        at org.obolibrary.macro.MacroExpansionVisitor.expandAll(MacroExpansionVisitor.java:95)
        at owltools.mooncat.SpeciesSubsetterUtil.<init>(SpeciesSubsetterUtil.java:139)
        at owltools.cli.CommandRunner.runSingleIteration(CommandRunner.java:759)
        at owltools.cli.CommandRunnerBase.run(CommandRunnerBase.java:76)
        at owltools.cli.CommandRunnerBase.run(CommandRunnerBase.java:68)
        at owltools.cli.CommandLineInterface.main(CommandLineInterface.java:12)

Can you help?

Thanks.

**Comment by kimrutherford** [comment]
Hi.  Is there a work-around for this problem?

@ValWood

**Comment by ValWood** [comment]
We can't update Canto with new terms :(

**Comment by cmungall** [comment]
Sorry not having much luck here

I can confirm I get the same error on the source file as well:

```
owltools --use-catalog go-edit.obo --reasoner elk --make-species-subset  -t NCBITaxon:4896 -o go-plus-pombe-only.owl
2017-06-01 23:36:43,852 INFO  (ManchesterSyntaxTool:130) parsing: Class: GO_0016116 DisjointWith: RO_0002162 some NCBITaxon_4896
2017-06-01 23:36:43,853 INFO  (MacroExpansionVisitor:182) Template to Expand Class: ?X DisjointWith: RO_0002162 some ?Y
2017-06-01 23:36:43,853 INFO  (MacroExpansionVisitor:185) Expanding Class: GO_0010205 DisjointWith: RO_0002162 some NCBITaxon_33208
2017-06-01 23:36:43,853 INFO  (ManchesterSyntaxTool:130) parsing: Class: GO_0010205 DisjointWith: RO_0002162 some NCBITaxon_33208
2017-06-01 23:36:43,854 INFO  (MacroExpansionVisitor:182) Template to Expand Class: ?X DisjointWith: RO_0002162 some ?Y
2017-06-01 23:36:43,854 INFO  (MacroExpansionVisitor:185) Expanding Class: GO_0061737 DisjointWith: RO_0002162 some NCBITaxon_4751
2017-06-01 23:36:43,854 INFO  (ManchesterSyntaxTool:130) parsing: Class: GO_0061737 DisjointWith: RO_0002162 some NCBITaxon_4751
2017-06-01 23:36:43,863 INFO  (MacroExpansionVisitor:182) Template to Expand Class: ?X DisjointWith: RO_0002162 some ?Y
2017-06-01 23:36:43,863 INFO  (MacroExpansionVisitor:185) Expanding Class: GO_0051644 DisjointWith: RO_0002162 some NCBITaxon_4751
2017-06-01 23:36:43,864 INFO  (ManchesterSyntaxTool:130) parsing: Class: GO_0051644 DisjointWith: RO_0002162 some NCBITaxon_4751
Exception in thread "main" java.lang.ClassCastException: uk.ac.manchester.cs.owl.owlapi.OWLLiteralImplString cannot be cast to org.semanticweb.owlapi.model.IRI
```

so based on the above it seems to be something to do with this line:

```
id: GO:0051644
name: plastid localization
...
relationship: never_in_taxon NCBITaxon:4751 {id="GOTAX:0000505", source="PMID:21311032"} ! Fungi
```

when I remove it, it complains about a different line

I tried replacing with a minimal ontology to reproduce the error:

```
ontology: x
import: http://purl.obolibrary.org/obo/go/imports/ncbitaxon_import.owl

[Term]
id: GO:0051644
name: plastid localization
namespace: biological_process
def: "Any process in which a plastid is transported to, and/or maintained in, a specific location within the cell." [GOC:ai]
synonym: "establishment and maintenance of plastid localization" EXACT []
synonym: "plastid localisation" EXACT [GOC:mah]
intersection_of: GO:0051179 ! localization
intersection_of: transports_or_maintains_localization_of GO:0009536 ! plastid
relationship: never_in_taxon NCBITaxon:28009 {id="GOTAX:0000506", source="PMID:21311032"}
relationship: never_in_taxon NCBITaxon:33208 {id="GOTAX:0000493", source="PMID:21311032"} ! Metazoa
relationship: never_in_taxon NCBITaxon:4751 {id="GOTAX:0000505", source="PMID:21311032"} ! Fungi
relationship: never_in_taxon NCBITaxon:554915 {id="GOTAX:0000507", source="PMID:21311032"} ! Amoebozoa

[Typedef]
id: in_taxon
name: in taxon
namespace: external
xref: RO:0002162

[Typedef]
id: never_in_taxon
name: never_in_taxon
namespace: external
xref: RO:0002161
expand_assertion_to: "Class: ?X DisjointWith: RO_0002162 some ?Y" []
is_metadata_tag: true
is_class_level: true
```

but this passes fine!

I'll try and step through this later in the debugger. It doesn't make any sense, the class cast to an IRI is dodgy, but in this it clearly is an IRI

**Comment by kimrutherford** [comment]
Hi Chris.

I had a look at the differences between the last go-plus.owl that worked and the first version that didn't.  The changes that make OWLTools fail seem to be the addition of lines like:

    <obo:RO_0002161 rdf:datatype="http://www.w3.org/2001/XMLSchema#string">&apos;cellular organisms&apos;</obo:RO_0002161>

If I take lines like that out of go-plus.owl then the command line above works.

There are lines like this too, that seem fine for OWLTools:

    <obo:RO_0002161 rdf:resource="http://purl.obolibrary.org/obo/NCBITaxon_4932"/>

Does that help narrow down the problem?

**Comment by ValWood** [comment]
thanks Chris, all working now ;)
