### ISSUE TITLE
Exception running owltools --make-species-subset

### ISSUE THREAD

**Issue by kimrutherford** [owlcollab/owltools#260]
Hi.

I'm getting an exception from owltools --make-species-subset using the go-plus.owl from here:
  http://purl.obolibrary.org/obo/go/extensions/go-plus.owl

Sorry if this is the wrong place to report the problem.  It's not clear from the exception whether it's my mistake or if it's an owltools or GO issue.

I don't get an exception if I use the current (2018-06-07) go-plus.owl from SVN.

This is the command line:

```sh
curl -L http://purl.obolibrary.org/obo/go/extensions/go-plus.owl > /tmp/go-plus.owl &&
 (cd go-svn/ontology/extensions; owltools /tmp/go-plus.owl --use-catalog --reasoner elk \
   --make-species-subset -t NCBITaxon:4896 -o -f obo /tmp/go-plus-pombe-only.obo)
```

The error is:

```
2018-06-12 00:05:40,661 WARN  (ChangeIndexingProcessor:66) [reasoner.indexing.axiomIgnored]ELK does not support InverseObjectProperties. Axiom ignored:
InverseObjectProperties(<http://purl.obolibrary.org/obo/RO_0002005> <http://purl.obolibrary.org/obo/RO_0002134>)
Exception in thread "main" java.lang.NullPointerException
        at org.obolibrary.obo2owl.OWLAPIObo2Owl.translateShorthandIdToExpandedId(OWLAPIObo2Owl.java:1766)
        at org.obolibrary.obo2owl.OWLAPIObo2Owl.oboIdToIRI_load(OWLAPIObo2Owl.java:1705)
        at org.obolibrary.obo2owl.OWLAPIObo2Owl.oboIdToIRI(OWLAPIObo2Owl.java:1670)
        at org.obolibrary.oboformat.writer.OBOFormatWriter$OWLOntologyNameProvider.getName(OBOFormatWriter.java:1182)
        at org.semanticweb.owlapi.oboformat.OBOFormatRenderer$1.getName(OBOFormatRenderer.java:74)
        at org.obolibrary.oboformat.writer.OBOFormatWriter.write(OBOFormatWriter.java:637)
        at org.obolibrary.oboformat.writer.OBOFormatWriter.write(OBOFormatWriter.java:363)
        at org.obolibrary.oboformat.writer.OBOFormatWriter.write(OBOFormatWriter.java:203)
        at org.semanticweb.owlapi.oboformat.OBOFormatRenderer.render(OBOFormatRenderer.java:88)
        at org.semanticweb.owlapi.oboformat.OBOFormatStorer.storeOntology(OBOFormatStorer.java:42)
        at org.semanticweb.owlapi.util.AbstractOWLStorer.storeOntology(AbstractOWLStorer.java:155)
        at org.semanticweb.owlapi.util.AbstractOWLStorer.storeOntology(AbstractOWLStorer.java:119)
        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.saveOntology(OWLOntologyManagerImpl.java:1521)
        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.saveOntology(OWLOntologyManagerImpl.java:1498)
        at owltools.io.ParserWrapper.saveOWL(ParserWrapper.java:289)
        at owltools.io.ParserWrapper.saveOWL(ParserWrapper.java:209)
        at owltools.cli.CommandRunner.runSingleIteration(CommandRunner.java:3708)
        at owltools.cli.CommandRunnerBase.run(CommandRunnerBase.java:76)
        at owltools.cli.CommandRunnerBase.run(CommandRunnerBase.java:68)
        at owltools.cli.CommandLineInterface.main(CommandLineInterface.java:12)
```

Here's the full output in case it helps:
  http://curation.pombase.org/kmr44/owltools-make-species-subset.log

Thanks.

**Comment by kimrutherford** [comment]
> I'm getting an exception from owltools --make-species-subset using the go-plus.owl from here:
> http://purl.obolibrary.org/obo/go/extensions/go-plus.owl

It works fine with today's version of go-plus.owl.
