### ISSUE TITLE
Help required: Nullpointer in TableToAxiomConverter

### ISSUE THREAD

**Issue by matentzn** [owlcollab/owltools#284]
I am trying to figure out why running this command fails:

```
cleaned/hp_hp.owl: sources
	owltools $(HP) $(MP) $(ZP) $(MP_G2P) $(HP_D2P) $(ZP_G2P) --merge-imports-closure --load-instances $(HP_D2P) --load-labels $(HP_DL) --merge-support-ontologies -o $@.tmp.owl && \
	owltools $@.tmp.owl --merge-import-closure --remove-disjoints --remove-equivalent-to-nothing-axioms -o $@
```

I don't need a solution, just a pointer on what to look for. All files referenced by the query exist and are parseable. My suspicion is that the problem appears [here](https://github.com/owlcollab/owltools/blob/452b4aa12665c79b94629d2e76b6b643a88e4537/OWLTools-Core/src/main/java/owltools/io/TableToAxiomConverter.java#L99), and somehow an empty row parsed from a table causes the whole issue. But before I launch myself into debugging, I wanted to give it another set of eyes before poking in the dark.

```
Exception in thread "main" java.lang.NullPointerException
        at com.carrotsearch.hppcrt.IteratorPool.borrow(IteratorPool.java:83)
        at com.carrotsearch.hppcrt.sets.ObjectHashSet.iterator(ObjectHashSet.java:808)
        at uk.ac.manchester.cs.owl.owlapi.HPPCSet.iterator(MapPointer.java:466)
        at uk.ac.manchester.cs.owl.owlapi.HPPCSet.addAll(MapPointer.java:514)
        at uk.ac.manchester.cs.owl.owlapi.HPPCSet.<init>(MapPointer.java:445)
        at uk.ac.manchester.cs.owl.owlapi.MapPointer.putInternal(MapPointer.java:324)
        at uk.ac.manchester.cs.owl.owlapi.MapPointer.put(MapPointer.java:239)
        at uk.ac.manchester.cs.owl.owlapi.Internals$1.visit(Internals.java:653)
        at uk.ac.manchester.cs.owl.owlapi.OWLClassImpl.accept(OWLClassImpl.java:253)
        at uk.ac.manchester.cs.owl.owlapi.AbstractEntityRegistrationManager.visit(AbstractEntityRegistrationManager.java:298)
        at uk.ac.manchester.cs.owl.owlapi.OWLClassAssertionAxiomImpl.accept(OWLClassAssertionAxiomImpl.java:123)
        at uk.ac.manchester.cs.owl.owlapi.Internals.addAxiom(Internals.java:649)
        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyImpl$OWLOntologyChangeFilter.visit(OWLOntologyImpl.java:141)
        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyImpl$OWLOntologyChangeFilter.visit(OWLOntologyImpl.java:114)
        at org.semanticweb.owlapi.model.AddAxiom.accept(AddAxiom.java:76)
        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyImpl.applyChange(OWLOntologyImpl.java:64)
        at uk.ac.manchester.cs.owl.owlapi.concurrent.ConcurrentOWLOntologyImpl.applyChange(ConcurrentOWLOntologyImpl.java:2194)
        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.enactChangeApplication(OWLOntologyManagerImpl.java:640)
        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.applyChanges(OWLOntologyManagerImpl.java:667)
        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.applyChange(OWLOntologyManagerImpl.java:817)
        at owltools.io.TableToAxiomConverter.addRow(TableToAxiomConverter.java:229)
        at owltools.io.TableToAxiomConverter.addRow(TableToAxiomConverter.java:224)
        at owltools.io.TableToAxiomConverter.parse(TableToAxiomConverter.java:109)
        at owltools.io.TableToAxiomConverter.parse(TableToAxiomConverter.java:95)
        at owltools.cli.CommandRunner.runSingleIteration(CommandRunner.java:4063)
        at owltools.cli.CommandRunnerBase.run(CommandRunnerBase.java:76)
        at owltools.cli.CommandRunnerBase.run(CommandRunnerBase.java:68)
        at owltools.cli.CommandLineInterface.main(CommandLineInterface.java:12)
make: *** [Makefile:121: cleaned/hp_hp.owl] Error 1
```

**Comment by matentzn** [comment]
Empty row was not the issue. Is there anyone here at owltools that could help me with this?

**Comment by matentzn** [comment]
Closing because I cant replicate in some environments. Maybe docker image related issue?
